---

# Naemon
- name: add repository key
  tags:
    - naemon
    - naemon_only
  apt_key: keyserver=keys.gnupg.net id='F8C1CA08A57B9ED7' state=present

- name: add naemon repository
  tags:
    - naemon
    - naemon_only
  apt_repository: repo='deb http://labs.consol.de/repo/stable/debian {{ansible_distribution_release}} main' update_cache=yes state=present

- name: install naemon and dependancies
  tags:
    - naemon
    - naemon_only
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - naemon
    - naemon-core
    - naemon-livestatus
    - nagios-plugins

- name: change naemon plugins directory
  tags:
    - naemon
    - naemon_only
  lineinfile: dest=/etc/naemon/resource.cfg regexp='/usr/lib/naemon/plugins$' line='$USER1$=/usr/lib/nagios/plugins' backrefs=yes
  notify: restart naemon

- name: set naemon configuration
  tags:
    - naemon
    - naemon_only
  template: src=naemon.cfg.j2 dest=/etc/naemon/naemon.cfg owner=naemon group=naemon mode=0644
  notify: restart naemon

- name: check naemon rights
  tags:
    - naemon
    - naemon_only
  file: path=/var/cache/naemon/live mode=777

# Thruk
- include: thruk.yml
  tags:
    - naemon
    - thruk
  when: install_thruk is defined and install_thruk

# PNPNagios
- include: pnp4nagios.yml
  tags:
    - naemon
    - pnp4nagios
  when: install_pnp4nagios is defined and install_pnp4nagios
